### ISSUE TITLE
Possible error running the readme code?

### ISSUE THREAD

**Issue by cmdcolin** [ihh/stockholm-js#1]
Created a project

yarn init
yarn add stockholm-js
create the README.md code in index.js
download Lysine.stock to current directory
node index.js

```
node index.js
Tree is ((AE013039.1/9145-9323:0.3910808817,AE001799.1/20444-20268:0.3376622139)node_116:0.5253933898,(AE006448.1/6071-6253:0.0940155812,(AF269536.1/680-500:0.2724450475,(AE016747.1/182196-182375:0.0080651569,(AF306669.1/1019-1194:0.0085335955,(AP003362.3/86114-86289:0.0044201319,(AP004826.1/205532-205707:0.0001051631,(AE016947.1/224792-224618:0.0216013901,(AE017274.1/20257-20449:0.0099521033,(AE017033.1/217118-217310:0.0130556605,(AE017007.1/287994-288186:0.0052067476,(AE010489.1/2647-2468:0.0141142610,(AE007856.1/5090-5262:0.2137752816,(AP003187.2/139222-139393:0.1221701288,(AE015944.1/195870-195703:0.0233508189,(AE004193.1/5679-5861:0.0249451096,(AE017154.1/86844-87014:0.0312858057,(AE007576.1/1562-1747:0.0628224203,(Z99121.2/6040-5861:0.1030279286,(AE013149.1/9167-9356:0.0767122527,(AL591976.1/186683-186486:0.0108633478,(AL596166.1/112469-112272:0.0040537632,(U32832.1/9495-9319:0.0430024152,(AE015937.1/285886-286061:0.0988472465,(AF270308.1/2156-2331:0.0211087990,(AP004827.1/261938-261763:0.0098767272,(AE007843.1/1920-1745:0.0257194872,(AP003194.2/187997-187828:0.0429137911,(AE015545.1/1265-1436:0.0934978146,(AP001517.1/215539-215348:0.1136029715,(AP001513.1/19957-19775:0.0386965374,(AP005076.1/290738-290918:0.1185087793,(AP004601.1/22341-22165:0.1238930952,(AP001512.1/119931-120105:0.1129613280,(AP005335.1/123141-123320:0.1028852530,(AE004361.1/7554-7382:0.0932529190,(AP001518.1/272531-272358:0.1471145915,(AE017000.1/234265-234084:0.0086453589,(AE017026.1/274819-274638:0.0125032137,(AE017267.1/95018-94836:0.0109416360,(M93419.1/332-511:0.0986816736,(J03294.1/2297-2476:0.0332320019,(AP003189.2/159236-159062:0.0961252166,(AP004598.1/253855-254037:0.1504648995,(AE006126.1/222-48:0.1424780559,(AE017029.1/246029-245843:0.0036184890,(AE017270.1/85304-85118:0.0082248886,(AE017003.1/180245-180059:0.0073439836,(AL935254.1/261916-262097:0.2049568888,(AE017269.1/77627-77808:0.0005521530,(AE017028.1/200117-200298:0.0007256834,(AE015829.1/4454-4280:0.0137411355,(AP005342.1/28132-28310:0.0098431157,(AP005082.1/169934-170112:0.0534519197,(AE004127.1/7715-7538:0.0087658364,(AE016770.1/235405-235209:0.0300185388,(X00008.1/296-492:0.0001615519,(U00006.1/98763-98567:0.0001000010,X15196.1/270-75:0.0211645370)node_60:0.0208146477)node_61:0.0003179659)node_62:0.5682781539)node_63:0.0907793738)node_64:0.0395011894)node_65:0.3653111406)node_66:0.8150272954)node_67:0.0004705034)node_68:0.1893322388)node_69:0.4974498996)node_70:0.0318101514)node_71:0.0039620552)node_72:0.3462339095)node_73:0.2318621806)node_74:0.1804652027)node_75:0.3907367381)node_76:0.1202422859)node_77:0.5063463732)node_78:0.0608076638)node_79:0.0009089909)node_80:0.3118689640)node_81:0.2640158710)node_82:0.2004379176)node_83:0.2590946109)node_84:0.2020955869)node_85:0.2856898497)node_86:0.4062047927)node_87:0.2326094051)node_88:0.2993848474)node_89:0.3853528708)node_90:0.1881174496)node_91:0.6318140703)node_92:0.1856734567)node_93:0.3919517912)node_94:0.2914760676)node_95:0.8053572692)node_96:0.0614436461)node_97:0.4465092521)node_98:0.2585299829)node_99:0.3191436763)node_100:0.5961160173)node_101:0.4073565007)node_102:0.5658135775)node_103:0.1959536193)node_104:0.1232262850)node_105:0.3213264571)node_106:0.7573510279)node_107:0.0174343884)node_108:0.0109886627)node_109:0.5119223578)node_110:0.9194599033)node_111:0.0001000010)node_112:0.0459985531)node_113:0.1515951036)node_114:0.6603579677)node_115:0.5723686206)node_117:0.5254007368)root;
Consensus structure is .....<<<<<<.....<<<<<<<<<............<<<<<<<<..................................>>>>>>>>........>>>.>.>>>>>...<<<<<<<<<<<<..............>>>>>>>>.>>>><<<.<<<<.<<<<.......>>>>.>>>>>>>.<<<<<<<.............................>>>>>>>.....>>>>>>.....
/home/cdiesh/t1/index.js:22
  console.warn ("Structure of " + seq + " is " + align.gr.SS[seq])
                                                            ^

TypeError: Cannot read property 'M93419.1/332-511' of undefined
    at Object.<anonymous> (/home/cdiesh/t1/index.js:22:61)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by ihh** [comment]
oops thanks
